name: Build & Test

on:
  push:
    branches:
      - main
      - dev
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build -c release

      - name: Unit Tests
        run: dotnet test -c release  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./test/Tfe.NetClient.Test/Tfe.NetClient.Test.csproj

      - name: Upload test coverage
        uses: codecov/codecov-action@v1
